Feature: Transform ETL extract data file and produce error and loadable files

  Scenario: The usual suspects
    Given an input file called "test.csv" with the following contents:
      """
      Zipcode,ZipCodeType,City,State,LocationType,Lat,Long,Location,Decommisioned
      6883,STANDARD,WESTON,CT,PRIMARY,41.22,-73.37,NA-US-CT-WESTON,FALSE
      6875,PO BOX,REDDING CENTER,CT,PRIMARY,41.3,-73.38,NA-US-CT-REDDING CENTER,FALSE
      6876,PO BOX,REDDING RIDGE,CT,PRIMARY,41.3,-73.38,NA-US-CT-REDDING RIDGE,FALSE
      6896,STANDARD,REDDING,CT,PRIMARY,41.3,-73.38,NA-US-CT-REDDING,FALSE
      6611,STANDARD,TRUMBULL,CT,PRIMARY,41.25,-73.2,NA-US-CT-TRUMBULL,FALSE
      7444,STANDARD,POMPTON PLAINS,NJ,PRIMARY,40.96,-74.3,NA-US-NJ-POMPTON PLAINS,FALSE
      7035,STANDARD,LINCOLN PARK,NJ,PRIMARY,40.92,-74.3,NA-US-NJ-LINCOLN PARK,FALSE
      7477,UNIQUE,WAYNE,NJ,PRIMARY,40.92,-74.27,NA-US-NJ-WAYNE,TRUE
      92809,STANDARD,ANAHEIM,CA,PRIMARY,33.86,-117.74,NA-US-CA-ANAHEIM,FALSE
      92808,STANDARD,ANAHEIM,CA,PRIMARY,33.84,-117.73,NA-US-CA-ANAHEIM,FALSE
      92886,STANDARD,YORBA LINDA,CA,PRIMARY,33.89,-117.78,NA-US-CA-YORBA LINDA,FALSE
      91709,STANDARD,CHINO HILLS,CA,PRIMARY,33.94,-117.72,NA-US-CA-CHINO HILLS,FALSE
      92807,STANDARD,ANAHEIM,CA,PRIMARY,33.85,-117.79,NA-US-CA-ANAHEIM,FALSE
      92817,PO BOX,ANAHEIM,CA,PRIMARY,33.85,-117.79,NA-US-CA-ANAHEIM,FALSE
      92823,STANDARD,BREA,CA,PRIMARY,33.92,-117.8,NA-US-CA-BREA,FALSE
      92885,PO BOX,YORBA LINDA,CA,PRIMARY,33.89,-117.82,NA-US-CA-YORBA LINDA,FALSE
      92862,STANDARD,ORANGE,CA,PRIMARY,33.79,-117.71,NA-US-CA-ORANGE,FALSE
      92867,STANDARD,ORANGE,CA,PRIMARY,33.81,-117.79,NA-US-CA-ORANGE,FALSE
      92880,STANDARD,CORONA,CA,PRIMARY,33.9,-117.61,NA-US-CA-CORONA,FALSE
      90703,STANDARD,CERRITOS,CA,PRIMARY,33.86,-118.05,NA-US-CA-CERRITOS,FALSE
      92811,PO BOX,ATWOOD,CA,PRIMARY,33.86,-117.83,NA-US-CA-ATWOOD,FALSE
      92859,PO BOX,ORANGE,CA,PRIMARY,33.8,-117.78,NA-US-CA-ORANGE,FALSE

      ,,,,,,,,
      1234A,NONSTANDARD,WESTON1,C1,NONPRIMARY,.22,.37,NA-US-CT+WESTON,TRU
      6883,STANDARD,WESTON,CT,PRIMARY,41.A2,-73.37,NA-US-CT-WESTON,FALSE
      6883,STANDARD,WESTON,CT,PRIMARY,41.22,-7Z.37,NA-US-CT-WESTON,FALSE
      6883,STANDARD,WESTON,CT,PRIMARY,41.22,+73.37,NA-US-CT-WESTON,FALSE
      """
    And an error file called "test.err"
    And a load file called "test.sql"
    When I transform the input file
    Then the error file should contain
      """
      Row 24  = []
      Blank row skipped
      Row 25  = ['', '', '', '', '', '', '', '', '']
      '' is an invalid zipcode
      '' is an invalid zipcode_type
      '' is an invalid city
      '' is an invalid state
      '' is an invalid location_type
      '' is an invalid latitude
      '' is an invalid longitude
      '' is an invalid location
      '' is an invalid decommissioned
      Row 26  = ['1234A', 'NONSTANDARD', 'WESTON1', 'C1', 'NONPRIMARY', '.22', '.37', 'NA-US-CT+WESTON', 'TRU']
      '1234A' is an invalid zipcode
      'NONSTANDARD' is an invalid zipcode_type
      'WESTON1' is an invalid city
      'C1' is an invalid state
      'NONPRIMARY' is an invalid location_type
      '.22' is an invalid latitude
      '.37' is an invalid longitude
      'NA-US-CT+WESTON' is an invalid location
      'TRU' is an invalid decommissioned
      Row 27  = ['06883', 'STANDARD', 'WESTON', 'CT', 'PRIMARY', '41.A2', '-73.37', 'NA-US-CT-WESTON', 'FALSE']
      '41.A2' is an invalid latitude
      Row 28  = ['06883', 'STANDARD', 'WESTON', 'CT', 'PRIMARY', '41.22', '-7Z.37', 'NA-US-CT-WESTON', 'FALSE']
      '-7Z.37' is an invalid longitude
      Row 29  = ['06883', 'STANDARD', 'WESTON', 'CT', 'PRIMARY', '41.22', '+73.37', 'NA-US-CT-WESTON', 'FALSE']
      '+73.37' is an invalid longitude
      """
    And the load file should contain
      """
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("06883","STANDARD","WESTON","CT","PRIMARY","41.22","-73.37","NA-US-CT-WESTON",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("06875","PO BOX","REDDING CENTER","CT","PRIMARY","41.30","-73.38","NA-US-CT-REDDING CENTER",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("06876","PO BOX","REDDING RIDGE","CT","PRIMARY","41.30","-73.38","NA-US-CT-REDDING RIDGE",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("06896","STANDARD","REDDING","CT","PRIMARY","41.30","-73.38","NA-US-CT-REDDING",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("06611","STANDARD","TRUMBULL","CT","PRIMARY","41.25","-73.20","NA-US-CT-TRUMBULL",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("07444","STANDARD","POMPTON PLAINS","NJ","PRIMARY","40.96","-74.30","NA-US-NJ-POMPTON PLAINS",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("07035","STANDARD","LINCOLN PARK","NJ","PRIMARY","40.92","-74.30","NA-US-NJ-LINCOLN PARK",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("07477","UNIQUE","WAYNE","NJ","PRIMARY","40.92","-74.27","NA-US-NJ-WAYNE",TRUE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92809","STANDARD","ANAHEIM","CA","PRIMARY","33.86","-117.74","NA-US-CA-ANAHEIM",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92808","STANDARD","ANAHEIM","CA","PRIMARY","33.84","-117.73","NA-US-CA-ANAHEIM",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92886","STANDARD","YORBA LINDA","CA","PRIMARY","33.89","-117.78","NA-US-CA-YORBA LINDA",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("91709","STANDARD","CHINO HILLS","CA","PRIMARY","33.94","-117.72","NA-US-CA-CHINO HILLS",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92807","STANDARD","ANAHEIM","CA","PRIMARY","33.85","-117.79","NA-US-CA-ANAHEIM",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92817","PO BOX","ANAHEIM","CA","PRIMARY","33.85","-117.79","NA-US-CA-ANAHEIM",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92823","STANDARD","BREA","CA","PRIMARY","33.92","-117.80","NA-US-CA-BREA",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92885","PO BOX","YORBA LINDA","CA","PRIMARY","33.89","-117.82","NA-US-CA-YORBA LINDA",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92862","STANDARD","ORANGE","CA","PRIMARY","33.79","-117.71","NA-US-CA-ORANGE",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92867","STANDARD","ORANGE","CA","PRIMARY","33.81","-117.79","NA-US-CA-ORANGE",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92880","STANDARD","CORONA","CA","PRIMARY","33.90","-117.61","NA-US-CA-CORONA",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("90703","STANDARD","CERRITOS","CA","PRIMARY","33.86","-118.05","NA-US-CA-CERRITOS",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92811","PO BOX","ATWOOD","CA","PRIMARY","33.86","-117.83","NA-US-CA-ATWOOD",FALSE);
      INSERT INTO ZIPCODES (ZIPCODE, ZIPCODE_TYPE, CITY, STATE, LOCATION_TYPE, LATITUDE, LONGITUDE, LOCATION, DECOMISSIONED) VALUES("92859","PO BOX","ORANGE","CA","PRIMARY","33.80","-117.78","NA-US-CA-ORANGE",FALSE);
      """
